// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabApp.Infrastructure.Persistence;

#nullable disable

namespace VocabApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513201951_AddPredefinedWordsTable")]
    partial class AddPredefinedWordsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VocabApp.Domain.Aggregates.PredefinedWordAggregate.PredefinedWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Original");

                    b.HasIndex("Field", "Category");

                    b.HasIndex("Field", "IsActive");

                    b.ToTable("PredefinedWords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b28f01b-18ec-4431-b1c6-097d6930fc89"),
                            AiSentence = "An algorithm is a step-by-step procedure for solving a problem.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9823),
                            Field = "Software",
                            IsActive = true,
                            Original = "algorithm",
                            Translation = "algoritma"
                        },
                        new
                        {
                            Id = new Guid("1b7a5571-9388-436e-ae9b-792959c973da"),
                            AiSentence = "A bug is an error or flaw in a software program.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9920),
                            Field = "Software",
                            IsActive = true,
                            Original = "bug",
                            Translation = "hata"
                        },
                        new
                        {
                            Id = new Guid("16b6999a-d974-48f5-9cdd-2a8221be9b39"),
                            AiSentence = "To debug means to find and fix errors in code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9928),
                            Field = "Software",
                            IsActive = true,
                            Original = "debug",
                            Translation = "hata ayıklamak"
                        },
                        new
                        {
                            Id = new Guid("72056339-4756-498f-a266-e05d77613a77"),
                            AiSentence = "A framework provides a foundation for building applications.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9936),
                            Field = "Software",
                            IsActive = true,
                            Original = "framework",
                            Translation = "framework"
                        },
                        new
                        {
                            Id = new Guid("a6265f55-78b6-495a-98cd-69588c5c58b3"),
                            AiSentence = "A repository is a central storage location for code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9942),
                            Field = "Software",
                            IsActive = true,
                            Original = "repository",
                            Translation = "depo"
                        },
                        new
                        {
                            Id = new Guid("084e7fe8-13c8-4773-9b85-eb054b6b549a"),
                            AiSentence = "Diagnosis is the identification of a disease or condition.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9976),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "diagnosis",
                            Translation = "tanı"
                        },
                        new
                        {
                            Id = new Guid("20fd5b19-adb8-49df-9786-b3118ae0c031"),
                            AiSentence = "Prognosis is the likely outcome of a disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 346, DateTimeKind.Utc).AddTicks(9983),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "prognosis",
                            Translation = "hastalık gidişi"
                        },
                        new
                        {
                            Id = new Guid("6287df7b-8098-4954-9289-ad6523e46c35"),
                            AiSentence = "A symptom is a sign of illness or disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(16),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "symptom",
                            Translation = "semptom"
                        },
                        new
                        {
                            Id = new Guid("6f1bcfdf-1fcd-4369-8d91-1c90c9c5b8cf"),
                            AiSentence = "Treatment is the medical care given for an illness.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(22),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "treatment",
                            Translation = "tedavi"
                        },
                        new
                        {
                            Id = new Guid("72d2cf05-3dce-4b16-b125-ada4365580ac"),
                            AiSentence = "A defendant is a person accused of a crime.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(30),
                            Field = "Law",
                            IsActive = true,
                            Original = "defendant",
                            Translation = "davalı"
                        },
                        new
                        {
                            Id = new Guid("759719e5-a651-4ad9-a67d-2ae778331e83"),
                            AiSentence = "A verdict is the decision made by a court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(35),
                            Field = "Law",
                            IsActive = true,
                            Original = "verdict",
                            Translation = "karar"
                        },
                        new
                        {
                            Id = new Guid("2ae720d9-5830-42b8-927d-997cdc5bc95a"),
                            AiSentence = "A lawsuit is a legal action brought in court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(40),
                            Field = "Law",
                            IsActive = true,
                            Original = "lawsuit",
                            Translation = "dava"
                        },
                        new
                        {
                            Id = new Guid("8d8343b9-de16-4113-9cd4-30614122a953"),
                            AiSentence = "An attorney is a lawyer who represents clients.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 13, 20, 19, 50, 347, DateTimeKind.Utc).AddTicks(45),
                            Field = "Law",
                            IsActive = true,
                            Original = "attorney",
                            Translation = "avukat"
                        });
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsMany("VocabApp.Domain.Entities.Badge", "_badges", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AwardedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserBadges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_badges");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.OwnsOne("VocabApp.Domain.ValueObjects.ReviewInfo", "Review", b1 =>
                        {
                            b1.Property<Guid>("WordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("EaseFactor")
                                .HasColumnType("real")
                                .HasColumnName("ReviewEaseFactor");

                            b1.Property<int>("IntervalDays")
                                .HasColumnType("int")
                                .HasColumnName("ReviewIntervalDays");

                            b1.Property<DateTime?>("LastReviewedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewLastReviewedAt");

                            b1.Property<DateTime>("NextReviewAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewNextReviewAt");

                            b1.Property<int>("Repetitions")
                                .HasColumnType("int")
                                .HasColumnName("ReviewRepetitions");

                            b1.HasKey("WordId");

                            b1.ToTable("Words");

                            b1.WithOwner()
                                .HasForeignKey("WordId");
                        });

                    b.Navigation("Review")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
