// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabApp.Infrastructure.Persistence;

#nullable disable

namespace VocabApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515174532_AddUserVocabularyProgress")]
    partial class AddUserVocabularyProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VocabApp.Domain.Aggregates.PredefinedWordAggregate.PredefinedWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Original");

                    b.HasIndex("Field", "Category");

                    b.HasIndex("Field", "IsActive");

                    b.ToTable("PredefinedWords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bca7af0e-6048-4038-a35a-023335c0bee8"),
                            AiSentence = "An algorithm is a step-by-step procedure for solving a problem.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2466),
                            Field = "Software",
                            IsActive = true,
                            Original = "algorithm",
                            Translation = "algoritma"
                        },
                        new
                        {
                            Id = new Guid("cf44c157-53ad-48b8-81c7-5e5e53bc9374"),
                            AiSentence = "A bug is an error or flaw in a software program.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2479),
                            Field = "Software",
                            IsActive = true,
                            Original = "bug",
                            Translation = "hata"
                        },
                        new
                        {
                            Id = new Guid("0c3cc2b1-0633-46d6-bd62-3d72d92d2988"),
                            AiSentence = "To debug means to find and fix errors in code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2483),
                            Field = "Software",
                            IsActive = true,
                            Original = "debug",
                            Translation = "hata ayıklamak"
                        },
                        new
                        {
                            Id = new Guid("02275182-c135-474d-9403-5f7c77716e5c"),
                            AiSentence = "A framework provides a foundation for building applications.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2486),
                            Field = "Software",
                            IsActive = true,
                            Original = "framework",
                            Translation = "framework"
                        },
                        new
                        {
                            Id = new Guid("356055e5-e47d-4d71-b0bf-b18e543126ba"),
                            AiSentence = "A repository is a central storage location for code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2490),
                            Field = "Software",
                            IsActive = true,
                            Original = "repository",
                            Translation = "depo"
                        },
                        new
                        {
                            Id = new Guid("ed9e1d2f-12f4-45bb-84e0-7cc6252fdb30"),
                            AiSentence = "Diagnosis is the identification of a disease or condition.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2504),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "diagnosis",
                            Translation = "tanı"
                        },
                        new
                        {
                            Id = new Guid("6a53fbf4-61b6-4f88-a842-f0504cbb8dff"),
                            AiSentence = "Prognosis is the likely outcome of a disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2509),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "prognosis",
                            Translation = "hastalık gidişi"
                        },
                        new
                        {
                            Id = new Guid("229e63c8-ef36-4b58-beed-498dd9b32e58"),
                            AiSentence = "A symptom is a sign of illness or disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2512),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "symptom",
                            Translation = "semptom"
                        },
                        new
                        {
                            Id = new Guid("e42922af-d212-4459-a317-73c5a806aad1"),
                            AiSentence = "Treatment is the medical care given for an illness.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2520),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "treatment",
                            Translation = "tedavi"
                        },
                        new
                        {
                            Id = new Guid("061be113-13f2-40eb-9c19-e405cc215e4a"),
                            AiSentence = "A defendant is a person accused of a crime.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2525),
                            Field = "Law",
                            IsActive = true,
                            Original = "defendant",
                            Translation = "davalı"
                        },
                        new
                        {
                            Id = new Guid("c38d48ab-e002-4283-b736-98f7c28c9f01"),
                            AiSentence = "A verdict is the decision made by a court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2529),
                            Field = "Law",
                            IsActive = true,
                            Original = "verdict",
                            Translation = "karar"
                        },
                        new
                        {
                            Id = new Guid("8b2e0123-1b72-4b21-be5f-8f223730103e"),
                            AiSentence = "A lawsuit is a legal action brought in court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2532),
                            Field = "Law",
                            IsActive = true,
                            Original = "lawsuit",
                            Translation = "dava"
                        },
                        new
                        {
                            Id = new Guid("8828ce07-34f7-485c-b4ff-0317e3b67e63"),
                            AiSentence = "An attorney is a lawyer who represents clients.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 15, 17, 45, 31, 173, DateTimeKind.Utc).AddTicks(2536),
                            Field = "Law",
                            IsActive = true,
                            Original = "attorney",
                            Translation = "avukat"
                        });
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.HasIndex("OwnerId", "Field");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VocabApp.Domain.Entities.UserVocabularyProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AverageTimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<int>("ConsecutiveSelections")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSelectedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MaxTimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<long>("MinTimeTakenMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LastSelectedAt");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("UserVocabularyProgresses");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsMany("VocabApp.Domain.Entities.Badge", "_badges", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AwardedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserBadges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_badges");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.OwnsOne("VocabApp.Domain.ValueObjects.ReviewInfo", "Review", b1 =>
                        {
                            b1.Property<Guid>("WordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("EaseFactor")
                                .HasColumnType("real")
                                .HasColumnName("ReviewEaseFactor");

                            b1.Property<int>("IntervalDays")
                                .HasColumnType("int")
                                .HasColumnName("ReviewIntervalDays");

                            b1.Property<DateTime?>("LastReviewedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewLastReviewedAt");

                            b1.Property<DateTime>("NextReviewAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewNextReviewAt");

                            b1.Property<int>("Repetitions")
                                .HasColumnType("int")
                                .HasColumnName("ReviewRepetitions");

                            b1.HasKey("WordId");

                            b1.ToTable("Words");

                            b1.WithOwner()
                                .HasForeignKey("WordId");
                        });

                    b.Navigation("Review")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
