// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabApp.Infrastructure.Persistence;

#nullable disable

namespace VocabApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VocabApp.Domain.Aggregates.PredefinedWordAggregate.PredefinedWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Original");

                    b.HasIndex("Field", "Category");

                    b.HasIndex("Field", "IsActive");

                    b.ToTable("PredefinedWords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9eec26d-4ad1-4788-82e3-e9e060ec81d8"),
                            AiSentence = "An algorithm is a step-by-step procedure for solving a problem.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5881),
                            Field = "Software",
                            IsActive = true,
                            Original = "algorithm",
                            Translation = "algoritma"
                        },
                        new
                        {
                            Id = new Guid("efa5d740-577a-4b2b-9e9b-b1926cdc9d8d"),
                            AiSentence = "A bug is an error or flaw in a software program.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5899),
                            Field = "Software",
                            IsActive = true,
                            Original = "bug",
                            Translation = "hata"
                        },
                        new
                        {
                            Id = new Guid("454b4275-6c87-4c55-ad76-0837d44993a5"),
                            AiSentence = "To debug means to find and fix errors in code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5904),
                            Field = "Software",
                            IsActive = true,
                            Original = "debug",
                            Translation = "hata ayıklamak"
                        },
                        new
                        {
                            Id = new Guid("8c2a3f5e-da7b-4052-ac2e-b73bc1bd7b10"),
                            AiSentence = "A framework provides a foundation for building applications.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5909),
                            Field = "Software",
                            IsActive = true,
                            Original = "framework",
                            Translation = "framework"
                        },
                        new
                        {
                            Id = new Guid("259b50bf-7c68-42f9-a671-64ab6b1b2281"),
                            AiSentence = "A repository is a central storage location for code.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5913),
                            Field = "Software",
                            IsActive = true,
                            Original = "repository",
                            Translation = "depo"
                        },
                        new
                        {
                            Id = new Guid("5d090354-b672-4635-a76d-93a01e782b29"),
                            AiSentence = "Diagnosis is the identification of a disease or condition.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5937),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "diagnosis",
                            Translation = "tanı"
                        },
                        new
                        {
                            Id = new Guid("a985bcd6-f85f-42c2-b4fc-fe5a80a32490"),
                            AiSentence = "Prognosis is the likely outcome of a disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5960),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "prognosis",
                            Translation = "hastalık gidişi"
                        },
                        new
                        {
                            Id = new Guid("3eb376f5-3412-4534-b342-03e3e13cab3a"),
                            AiSentence = "A symptom is a sign of illness or disease.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5965),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "symptom",
                            Translation = "semptom"
                        },
                        new
                        {
                            Id = new Guid("4a5f9438-b2a4-46be-8be7-5cb8c775309d"),
                            AiSentence = "Treatment is the medical care given for an illness.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5969),
                            Field = "Medicine",
                            IsActive = true,
                            Original = "treatment",
                            Translation = "tedavi"
                        },
                        new
                        {
                            Id = new Guid("d8bc78d6-767c-44b1-9c49-8c8ea0d70983"),
                            AiSentence = "A defendant is a person accused of a crime.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5976),
                            Field = "Law",
                            IsActive = true,
                            Original = "defendant",
                            Translation = "davalı"
                        },
                        new
                        {
                            Id = new Guid("9518b5d7-3aea-4c4b-b001-969cef8b84ce"),
                            AiSentence = "A verdict is the decision made by a court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5981),
                            Field = "Law",
                            IsActive = true,
                            Original = "verdict",
                            Translation = "karar"
                        },
                        new
                        {
                            Id = new Guid("c207887d-8c34-4b75-9065-c0f759e0bc50"),
                            AiSentence = "A lawsuit is a legal action brought in court.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5986),
                            Field = "Law",
                            IsActive = true,
                            Original = "lawsuit",
                            Translation = "dava"
                        },
                        new
                        {
                            Id = new Guid("2eb089a7-4d99-4778-bde9-35ea32e46939"),
                            AiSentence = "An attorney is a lawyer who represents clients.",
                            Category = "General",
                            CreatedAt = new DateTime(2026, 5, 14, 20, 20, 46, 634, DateTimeKind.Utc).AddTicks(5991),
                            Field = "Law",
                            IsActive = true,
                            Original = "attorney",
                            Translation = "avukat"
                        });
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyGoal")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSentence")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Field")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "CreatedAt");

                    b.HasIndex("OwnerId", "Field");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.OwnsMany("VocabApp.Domain.Entities.Badge", "_badges", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AwardedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserBadges", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_badges");
                });

            modelBuilder.Entity("VocabApp.Domain.Aggregates.WordAggregate.Word", b =>
                {
                    b.OwnsOne("VocabApp.Domain.ValueObjects.ReviewInfo", "Review", b1 =>
                        {
                            b1.Property<Guid>("WordId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("EaseFactor")
                                .HasColumnType("real")
                                .HasColumnName("ReviewEaseFactor");

                            b1.Property<int>("IntervalDays")
                                .HasColumnType("int")
                                .HasColumnName("ReviewIntervalDays");

                            b1.Property<DateTime?>("LastReviewedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewLastReviewedAt");

                            b1.Property<DateTime>("NextReviewAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReviewNextReviewAt");

                            b1.Property<int>("Repetitions")
                                .HasColumnType("int")
                                .HasColumnName("ReviewRepetitions");

                            b1.HasKey("WordId");

                            b1.ToTable("Words");

                            b1.WithOwner()
                                .HasForeignKey("WordId");
                        });

                    b.Navigation("Review")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
